"""
Test Klavis with the MockMidiInput source.

This test verifies that the KlavisServer correctly receives and dispatches
events generated by the mock input source.
"""

import unittest
import threading
import time

from klavis.event import MidiEvent
from klavis.input import MockMidiInput
from klavis.server import KlavisServer


class TestMockInput(unittest.TestCase):
    def test_event_dispatch(self):
        received = []

        def callback(event: MidiEvent):
            received.append(event)
            server.stop()

        server = KlavisServer(MockMidiInput())
        server.register_callback(callback)

        thread = threading.Thread(target=server.start)
        thread.start()

        # Allow up to 2 seconds for the mock to generate an event
        thread.join(timeout=2)

        self.assertTrue(len(received) > 0, "No MIDI event received")
        self.assertIsInstance(received[0], MidiEvent)


if __name__ == "__main__":
    unittest.main()

